spring:
  datasource:
    url: ENC(Ks0if6ECN0jHt7UfXvHn8KFlTn5VThkKcFRCw+xbmS3tuAfPDKLtOAAvAVW+UKtgdrGKurzYpDPiiGFvgY8ySu+Aw2H1LUDP3gsefcFafGlIbjwqTdrxXIt8dCMFQ77nO95rJ8JUVGrgpF85aNDdUI27tyMd3oBoHdVQvXtVtOA/8RsYhSkY4A==)
    username: ENC(nPPrAxI97Ml5W5C5+t5EKFmDGZ0CsD7A)
    password: ENC(n5zVEZTCQop7Tosnzumr2hhUOCICUHqg)
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
